[2024-07-26 22:40:02,494] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: grillos_operations.create_schemas 2024-07-26T22:39:00.582770+00:00 [queued]>
[2024-07-26 22:40:02,517] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: grillos_operations.create_schemas 2024-07-26T22:39:00.582770+00:00 [queued]>
[2024-07-26 22:40:02,518] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 22:40:02,518] {taskinstance.py:1088} INFO - Starting attempt 2 of 5
[2024-07-26 22:40:02,518] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 22:40:02,531] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): create_schemas> on 2024-07-26T22:39:00.582770+00:00
[2024-07-26 22:40:02,534] {standard_task_runner.py:52} INFO - Started process 200 to run task
[2024-07-26 22:40:02,538] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'grillos_operations', 'create_schemas', '2024-07-26T22:39:00.582770+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmplwpxifyv', '--error-file', '/tmp/tmpakf90202']
[2024-07-26 22:40:02,540] {standard_task_runner.py:77} INFO - Job 3: Subtask create_schemas
[2024-07-26 22:40:02,598] {logging_mixin.py:104} INFO - Running <TaskInstance: grillos_operations.create_schemas 2024-07-26T22:39:00.582770+00:00 [running]> on host 7abc9a149374
[2024-07-26 22:40:02,705] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=grillos_operations
AIRFLOW_CTX_TASK_ID=create_schemas
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T22:39:00.582770+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-26T22:39:00.582770+00:00
[2024-07-26 22:40:02,708] {postgres.py:68} INFO - Executing: 
    BEGIN;
    CREATE SCHEMA IF NOT EXISTS bronze;
    CREATE SCHEMA IF NOT EXISTS silver;
    CREATE SCHEMA IF NOT EXISTS gold;
    COMMIT;
    
[2024-07-26 22:40:02,744] {base.py:78} INFO - Using connection to: id: ***_default. Host: ***, Port: None, Schema: ***, Login: ***, Password: ***, extra: {}
[2024-07-26 22:40:10,757] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Temporary failure in name resolution

[2024-07-26 22:40:10,778] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=grillos_operations, task_id=create_schemas, execution_date=20240726T223900, start_date=20240726T224002, end_date=20240726T224010
[2024-07-26 22:40:10,862] {local_task_job.py:149} INFO - Task exited with return code 1
