[2024-07-26 23:14:40,776] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: grillos_operations.create_schemas 2024-07-26T23:14:39.214881+00:00 [queued]>
[2024-07-26 23:14:40,799] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: grillos_operations.create_schemas 2024-07-26T23:14:39.214881+00:00 [queued]>
[2024-07-26 23:14:40,799] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 23:14:40,800] {taskinstance.py:1088} INFO - Starting attempt 1 of 4
[2024-07-26 23:14:40,800] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-26 23:14:40,812] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): create_schemas> on 2024-07-26T23:14:39.214881+00:00
[2024-07-26 23:14:40,816] {standard_task_runner.py:52} INFO - Started process 198 to run task
[2024-07-26 23:14:40,820] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'grillos_operations', 'create_schemas', '2024-07-26T23:14:39.214881+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp7g687d7y', '--error-file', '/tmp/tmpg0gac_nz']
[2024-07-26 23:14:40,823] {standard_task_runner.py:77} INFO - Job 2: Subtask create_schemas
[2024-07-26 23:14:40,873] {logging_mixin.py:104} INFO - Running <TaskInstance: grillos_operations.create_schemas 2024-07-26T23:14:39.214881+00:00 [running]> on host 8fb633b6e8b9
[2024-07-26 23:14:40,938] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=grillos_operations
AIRFLOW_CTX_TASK_ID=create_schemas
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T23:14:39.214881+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-26T23:14:39.214881+00:00
[2024-07-26 23:14:40,939] {postgres.py:68} INFO - Executing: 
    BEGIN;
    CREATE SCHEMA IF NOT EXISTS bronze;
    CREATE SCHEMA IF NOT EXISTS silver;
    CREATE SCHEMA IF NOT EXISTS gold;
    COMMIT;
    
[2024-07-26 23:14:40,957] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 70, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_grillos` isn't defined
[2024-07-26 23:14:40,960] {taskinstance.py:1551} INFO - Marking task as UP_FOR_RETRY. dag_id=grillos_operations, task_id=create_schemas, execution_date=20240726T231439, start_date=20240726T231440, end_date=20240726T231440
[2024-07-26 23:14:40,992] {local_task_job.py:149} INFO - Task exited with return code 1
